<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Postal Code_postCodeInput</name>
   <tag></tag>
   <elementGuidId>86d3388a-28a6-4df8-b287-169984699782</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#postCodeInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='postCodeInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>935b92cf-2c85-421c-adf3-364fc0974852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>postal-code</value>
      <webElementGuid>ca6c9039-7691-43a3-a552-6c6a9dbdc387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>postCodeInput</value>
      <webElementGuid>130d6831-7f98-4e86-af38-baff03dab4d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input optimizedCheckout-form-input</value>
      <webElementGuid>741c3579-523c-4aa5-aac1-5f60fe9827bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5686c9eb-e56a-4891-b152-e72164fcc58a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;postCodeInput&quot;)</value>
      <webElementGuid>73e1b61a-02bd-4c6f-b2ae-34b19de06d44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='postCodeInput']</value>
      <webElementGuid>6c042041-cf58-471d-a9f1-3c8847ec2ca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='checkoutShippingAddress']/div/div/div[5]/div/input</value>
      <webElementGuid>4d5fc408-2eaf-49e8-9705-84d4e3f29e56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>fb8ab51a-8ce9-49aa-9935-1c45d7d586f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'postCodeInput' and @type = 'text']</value>
      <webElementGuid>ff499145-cd31-4131-86fc-a61070a6869c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
