<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name_lastNameInput</name>
   <tag></tag>
   <elementGuidId>97a506e4-f155-47c8-a46f-2ffac7f93b88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lastNameInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lastNameInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>853fdf17-716f-4283-8c37-4eff8f2223d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>family-name</value>
      <webElementGuid>625e1c95-4973-4efa-91a9-a5c06e088e77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lastNameInput</value>
      <webElementGuid>3000264f-c0d1-4790-8f36-24b892730d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input optimizedCheckout-form-input</value>
      <webElementGuid>1022a027-4af8-4da2-9566-99b910d6d9b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>69a94a83-ee8d-4bd4-8c39-363527a4c603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lastNameInput&quot;)</value>
      <webElementGuid>728e7a99-5d86-4552-977e-d789c195e4ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lastNameInput']</value>
      <webElementGuid>aa46fb27-e087-424e-bd89-6d1f1f03ce52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='checkoutShippingAddress']/div/div/div[2]/div/input</value>
      <webElementGuid>f8b16a93-ae78-4160-bfd5-c18cc145ebfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>0d45351e-59d3-4b13-abb2-a88c03ee7b35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'lastNameInput' and @type = 'text']</value>
      <webElementGuid>4a272a6b-56ee-48f1-b8db-465f1a9aa058</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
