<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address_addressLine1Input</name>
   <tag></tag>
   <elementGuidId>d6c4f831-8554-4b1b-ba69-d92aed096482</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addressLine1Input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addressLine1Input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e287cdf-6d9a-408e-9145-f8165dce472d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>address-line1</value>
      <webElementGuid>ac83fa46-dfd6-4dc5-911d-4bc0e500c74f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addressLine1Input</value>
      <webElementGuid>4c4cfa6b-0b38-4228-8f36-c76b981376f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input optimizedCheckout-form-input</value>
      <webElementGuid>c8001d89-953e-4b46-9ff7-e4843c1abcbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>731c2f44-1804-4049-8253-a308dedbb08e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressLine1Input&quot;)</value>
      <webElementGuid>8c18062c-fbed-40d9-90bf-abfe40c53739</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addressLine1Input']</value>
      <webElementGuid>be2a4235-280d-4cbf-9239-b7987ce7be6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='checkoutShippingAddress']/div/div/div[3]/div/input</value>
      <webElementGuid>fe2b6024-3592-4fc5-b381-f52574e4d171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>279f3d05-3b60-4f7d-97fb-b132b0a57a40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'addressLine1Input' and @type = 'text']</value>
      <webElementGuid>eaceec09-7685-430b-ad1a-f54c6118adc6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
