<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>legend_Your Order has been successfully placed</name>
   <tag></tag>
   <elementGuidId>30529f67-7b72-44e1-8c8c-68f0c8c2a019</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#confirmation-message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//legend[@id='confirmation-message']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>legend</value>
      <webElementGuid>da637efa-5830-4c73-9541-08e06009a58b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmation-message</value>
      <webElementGuid>6f9e4558-f807-4d83-8cb1-fca7a1d9901a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-legend optimizedCheckout-headingSecondary</value>
      <webElementGuid>35288868-77d4-44cd-8c7d-ade9033af69a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>shipping-address-heading</value>
      <webElementGuid>48a6e511-3444-4c90-b681-09060604c7e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your Order has been successfully placed.</value>
      <webElementGuid>4ed13276-0d19-483c-8228-2f6f3641c1d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmation-message&quot;)</value>
      <webElementGuid>22a1223a-ffac-4238-8f38-b1e152577e4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//legend[@id='confirmation-message']</value>
      <webElementGuid>937546ff-0287-4831-ab7a-4d451e8ffcfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-app']/div/div/div/ol/li/div/div/div/legend</value>
      <webElementGuid>420d9d27-4038-4d5d-beb4-3f2cdf9cc869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='StackDemo'])[2]/following::legend[1]</value>
      <webElementGuid>082490b5-adda-47d5-99a2-275216e86e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download order receipt'])[1]/preceding::legend[1]</value>
      <webElementGuid>f2c9a758-131e-4ea7-a7ad-c546d356f242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Your Order has been successfully placed.']/parent::*</value>
      <webElementGuid>7c1f44ae-d766-45c5-b560-d709e65a53ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//legend</value>
      <webElementGuid>fe22efd6-9a6f-4207-b6b4-b5744117d3c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//legend[@id = 'confirmation-message' and (text() = 'Your Order has been successfully placed.' or . = 'Your Order has been successfully placed.')]</value>
      <webElementGuid>09b15263-f649-433b-9fe7-06cc6c86a5b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
