<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add Product 3 to cart</name>
   <tag></tag>
   <elementGuidId>6831b914-e85e-4dab-8a5c-74b3ed82552b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#17 > div.shelf-item__buy-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='17']/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1290e58b-6d33-44c1-ad37-07a82d6b0277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shelf-item__buy-btn</value>
      <webElementGuid>27584d02-e01c-41a4-9e6f-a15b3e6f1bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to cart</value>
      <webElementGuid>2f9a468f-2c20-4dc5-a521-7e21aec41e64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;17&quot;)/div[@class=&quot;shelf-item__buy-btn&quot;]</value>
      <webElementGuid>168fe825-d07e-4fb0-91db-af3736e84829</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='17']/div[4]</value>
      <webElementGuid>36197b3e-b38a-49f9-9b4f-b9c70c41d14f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[18]/preceding::div[3]</value>
      <webElementGuid>ef441e92-6861-4344-adf7-a40c3775d1be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='.00'])[18]/preceding::div[3]</value>
      <webElementGuid>a8f72a81-db51-4466-8a20-73d51675a0c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/div[4]</value>
      <webElementGuid>08b5ff47-228e-4e9d-9864-f092a21d4149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Add to cart' or . = 'Add to cart')]</value>
      <webElementGuid>bf9bc136-06bd-47dd-90af-ad555a9be9ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
