<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add Product 1 to cart</name>
   <tag></tag>
   <elementGuidId>3c3aa3b6-4412-45cc-843a-c90a51e716f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#3 > div.shelf-item__buy-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='3']/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dc51ff48-5646-474d-a00e-79b5fd7f8d7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shelf-item__buy-btn</value>
      <webElementGuid>2bdebdb6-ac3e-4e96-9a7c-c684e5e54701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to cart</value>
      <webElementGuid>422ccf19-e3f1-4fd6-97f0-69ca75278233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;3&quot;)/div[@class=&quot;shelf-item__buy-btn&quot;]</value>
      <webElementGuid>7e67d219-5786-49b3-a0a4-92995155f324</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='3']/div[4]</value>
      <webElementGuid>d991d4d2-6e99-42b3-b9f8-db923b071233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[4]/preceding::div[3]</value>
      <webElementGuid>19202fb6-5985-4755-8120-167ad30a9f0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='.00'])[4]/preceding::div[3]</value>
      <webElementGuid>7cff98f1-302f-482f-bd2b-a012580b2a56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[4]</value>
      <webElementGuid>500a3e38-ed1c-4156-a60b-676f1053e6b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Add to cart' or . = 'Add to cart')]</value>
      <webElementGuid>b27e1327-eb86-4bad-b6f5-7fd53c6fec63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
