<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add Product 2 to cart</name>
   <tag></tag>
   <elementGuidId>903767c1-95d3-40a0-9d9c-41be03b6af9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#11 > div.shelf-item__buy-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='11']/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fdda30dc-dd1f-4189-ae43-be28d15c8dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shelf-item__buy-btn</value>
      <webElementGuid>40ae9cc3-ba43-4f18-8f95-95601514fc88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to cart</value>
      <webElementGuid>0b835fcc-7d94-4ef1-84cb-8f8e60f0816f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;11&quot;)/div[@class=&quot;shelf-item__buy-btn&quot;]</value>
      <webElementGuid>c47d4831-d553-4b06-9e9f-c6ab7b442039</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='11']/div[4]</value>
      <webElementGuid>b1e7d321-4a66-44f7-820d-a79de57a491b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[12]/preceding::div[3]</value>
      <webElementGuid>40e33e48-9892-4a63-adb8-96444a49aad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='.00'])[12]/preceding::div[3]</value>
      <webElementGuid>973065ec-d3f0-4b55-a2bb-8c96b167ed95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div[4]</value>
      <webElementGuid>b038643a-bab8-44b0-bf38-480de040a59d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Add to cart' or . = 'Add to cart')]</value>
      <webElementGuid>a6b87e60-cfa8-44c2-9827-8ef604cdc101</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
