<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_minus</name>
   <tag></tag>
   <elementGuidId>758a1cfa-df45-4933-b8cb-90628c85a382</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.change-product-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div[2]/div[2]/div[2]/div/div[4]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f7a7f5d4-950d-4992-82ff-2c833dee467c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>change-product-button</value>
      <webElementGuid>697eaa5c-6e5e-451a-bdce-cca4b20e1100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>1d934d8b-cbf7-4006-ae22-63394cdb442a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;App&quot;]/div[@class=&quot;float-cart float-cart--open&quot;]/div[@class=&quot;float-cart__content&quot;]/div[@class=&quot;float-cart__shelf-container&quot;]/div[@class=&quot;shelf-item&quot;]/div[@class=&quot;shelf-item__price&quot;]/div[1]/button[@class=&quot;change-product-button&quot;]</value>
      <webElementGuid>4b264e0d-6093-488b-9d86-377e42f17d95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[2]/div[2]/div/div[4]/div/button</value>
      <webElementGuid>4d0eab9f-b17d-4689-af1d-7ae9780f52de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bag'])[1]/following::button[1]</value>
      <webElementGuid>a0c19d37-21e4-4614-a4b3-2c44b5ab81f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[1]/following::button[1]</value>
      <webElementGuid>f8bf3163-60ac-4a60-be31-5791b95be176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/preceding::button[1]</value>
      <webElementGuid>372badaf-84ab-414f-a9c8-8dc39a95f4d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUBTOTAL'])[1]/preceding::button[2]</value>
      <webElementGuid>ea921313-7bba-4d89-95c5-e3010449f5ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='-']/parent::*</value>
      <webElementGuid>bfecac6e-8169-4511-af48-f2e5b6415d79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/div/button</value>
      <webElementGuid>b4fd0fd4-4a4c-4ee9-9b50-d41901125f53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '-' or . = '-')]</value>
      <webElementGuid>7f17584d-42d4-477e-95fe-be3b5d366ba1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
