<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Total product 0</name>
   <tag></tag>
   <elementGuidId>16a76b99-7266-41ee-9027-10f7809a2f64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.sub-price__val</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div[2]/div[2]/div[3]/div[2]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>a704fcc0-ace9-40c3-88de-1511264d5594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sub-price__val</value>
      <webElementGuid>b2074e8e-8b19-4203-a1e1-b4adc11c061b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$ 0.00</value>
      <webElementGuid>2ea4593e-4927-4f65-aafc-dbecabd3b24f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;App&quot;]/div[@class=&quot;float-cart float-cart--open&quot;]/div[@class=&quot;float-cart__content&quot;]/div[@class=&quot;float-cart__footer&quot;]/div[@class=&quot;sub-price&quot;]/p[@class=&quot;sub-price__val&quot;]</value>
      <webElementGuid>a8b25090-e408-4839-8836-a8306c64a656</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div[2]/div[3]/div[2]/p</value>
      <webElementGuid>d2e405f1-32a5-4f8e-85d0-fafe1d62ca6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUBTOTAL'])[1]/following::p[1]</value>
      <webElementGuid>5ee2e677-7ee1-4455-a877-9cc2871de5ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bag'])[1]/following::p[2]</value>
      <webElementGuid>c71b9bfc-df95-4a4d-8cfa-103c3bfb1e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue Shopping'])[1]/preceding::p[1]</value>
      <webElementGuid>95828ede-8db2-4981-ba0c-f6b4bce98a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2020 BrowserStack. All rights reserved.'])[1]/preceding::p[1]</value>
      <webElementGuid>cc4215a4-a519-4b2a-8ad5-56232db6adf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$ 0.00']/parent::*</value>
      <webElementGuid>f4b826ac-edb4-493a-af19-359106805303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/p</value>
      <webElementGuid>00b24c9f-7289-49b3-9bc1-d4f0345ebe05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '$ 0.00' or . = '$ 0.00')]</value>
      <webElementGuid>129dba86-5b60-4c12-9f08-e37ae71cf105</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
