name: Katalon Test Automation

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Download Katalon
      run: |
        wget https://github.com/katalon-studio/katalon/releases/download/v9.0.0/Katalon_Studio_Linux_64-10.1.0.tar.gz
        tar -xvf Katalon_Studio_Linux_64-9.0.0.tar.gz

    - name: Run Katalon Test
      run: |
        ./Katalon_Studio/katalonc -noSplash -runMode=console \
        -projectPath="$(pwd)/WEB-Project.prj" \
        -retry=0 -testSuitePath="Test Suites/Login" -executionProfile="default" -browserType="Chrome"

