<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Invalid Username</name>
   <tag></tag>
   <elementGuidId>9754a872-6f38-47b7-9add-7a2e0ea4387b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3.api-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div/form/div[2]/h3</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Invalid Username' or . = 'Invalid Username')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>9f39688b-80d0-49e2-ad01-b23d9d3e30e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>api-error</value>
      <webElementGuid>f539b777-afd8-48dc-b47e-4029d3684576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invalid Username</value>
      <webElementGuid>62ecf46b-370f-4c12-81b4-ea002b6b0ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;login_wrapper&quot;]/div[@class=&quot;Modal_modal__3I0HK&quot;]/form[@class=&quot;w-80 flex flex-col justify-between p-3&quot;]/div[@class=&quot;flex flex-col space-y-3&quot;]/h3[@class=&quot;api-error&quot;]</value>
      <webElementGuid>c4784eaf-1b0e-4da6-82be-14bf5cebb2ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/form/div[2]/h3</value>
      <webElementGuid>15bb319c-fdb9-440f-9d69-767f3b682222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log In'])[1]/following::h3[1]</value>
      <webElementGuid>4fa33b47-02b3-453f-9011-13203767a349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='testingisfun99'])[1]/following::h3[1]</value>
      <webElementGuid>d753da24-8eb0-4295-b594-c736a441d3cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Invalid Username']/parent::*</value>
      <webElementGuid>2c98a0f2-c7d5-4541-af8c-1c7d0e218aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>01bd937f-e072-4f03-a676-7caf8b08aaa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Invalid Username' or . = 'Invalid Username')]</value>
      <webElementGuid>8c5a2451-2994-48c2-aeb1-99291892bfce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
