<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Invalid Password</name>
   <tag></tag>
   <elementGuidId>4b9fdc52-13ed-4114-8a81-66c50672be61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3.api-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div/form/div[2]/h3</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Invalid Password' or . = 'Invalid Password')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>e5ae74e4-2165-4f36-aad7-4586dcd59c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>api-error</value>
      <webElementGuid>eb3c02f0-665a-453a-9b5d-387146a559fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invalid Password</value>
      <webElementGuid>d2b05c96-600a-46dc-9f42-3c8704dbffdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;login_wrapper&quot;]/div[@class=&quot;Modal_modal__3I0HK&quot;]/form[@class=&quot;w-80 flex flex-col justify-between p-3&quot;]/div[@class=&quot;flex flex-col space-y-3&quot;]/h3[@class=&quot;api-error&quot;]</value>
      <webElementGuid>4a105ecc-f89e-41a1-95a5-7e731ec57f87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/form/div[2]/h3</value>
      <webElementGuid>535d9692-9c04-4ffd-a6bb-f60233c974a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log In'])[1]/following::h3[1]</value>
      <webElementGuid>2be0e604-0044-4514-ade6-236121813ba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='invalid'])[1]/following::h3[1]</value>
      <webElementGuid>28e1678a-73d9-4e42-b43b-914984a0d122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Invalid Password']/parent::*</value>
      <webElementGuid>a47acc2b-5352-4816-9814-1c7fb8f5d100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>25b00b29-b4e3-49e2-9edc-2e54bdc24034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Invalid Password' or . = 'Invalid Password')]</value>
      <webElementGuid>6204c1ea-9652-4fa8-b6d3-0101cb09223f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
